### ISSUE TITLE
Ingress for server

### ISSUE THREAD

**Issue by jalberto** [rudderlabs/rudderstack-helm#17]
Currently, the way to make the server accessible is to set `service.type` to `loadBalancer`, it will be great to set up an optional `ingress` (with annotations) so it can all be deployed at once

**Comment by snarkychef** [comment]
Can you elaborate more on your requirement for an ingress? Are you planning to use custom ingress controller?

**Comment by jalberto** [comment]
yes, currently I am using traefik as ingress, this requires an additional definition file. Here an example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/browser-xss-filter: "true"
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    kubernetes.io/ingress.class: traefik
  labels:
    app: rud-rudderstack
    release: rud
  name: rud-rudderstack
  namespace: ops
spec:
  rules:
  - host: rudder.domain.com
    http:
      paths:
      - backend:
          serviceName: rud-rudderstack
          servicePort: 80
        path: /
```
